# Generated by Django 6.0 on 2026-03-19 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_adress_address'),
        ('userprofile', '0004_userprofile_user_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userprofile_address', to='core.address'),
        ),
    ]
