# Generated by Django 6.0 on 2026-02-04 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='website',
            field=models.CharField(blank=True, default='No website', max_length=255, null=True),
        ),
    ]
