# Generated by Django 6.0 on 2026-02-23 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_note_created_at_note_created_by_note_modified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='clients/profile_pictures/%Y/%m/%d/'),
        ),
    ]
