# Generated by Django 6.0 on 2026-02-23 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_client_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('active', 'Active'), ('inactive', 'Inactive'), ('on_hold', 'On Hold'), ('former', 'Former'), ('vip', 'VIP')], default='new', max_length=25),
        ),
    ]
