# Generated by Django 6.0 on 2026-03-19 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_client_status'),
        ('core', '0002_rename_adress_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.address'),
        ),
    ]
