# Generated by Django 6.0 on 2026-05-28 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_client_assigned_to'),
        ('core', '0005_googlecalendarcredential'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='address',
            field=models.ForeignKey(blank=True, help_text='Adress of the client', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='core.address'),
        ),
        migrations.AddField(
            model_name='client',
            name='last_contacted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
