# Generated by Django 6.0 on 2026-06-11 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_team_invite_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='invite_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
