# Generated by Django 6.0 on 2026-03-18 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_client_status'),
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='client.client'),
        ),
    ]
