# Generated by Django 6.0 on 2026-03-20 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_alter_client_client_address'),
        ('emails', '0002_emaillog_client'),
        ('lead', '0007_lead_previous_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillog',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.client'),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='lead',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails', to='lead.lead'),
        ),
    ]
