# Generated by Django 6.0 on 2026-03-20 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_alter_client_client_address'),
        ('emails', '0003_alter_emaillog_client_alter_emaillog_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillog',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.client'),
        ),
    ]
