# Generated by Django 6.0 on 2026-02-24 11:40

import lead.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0004_leadnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='checklist',
            field=models.JSONField(default=lead.models.get_default_checklist),
        ),
    ]
