# Generated by Django 6.0 on 2026-03-09 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0005_lead_checklist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lead',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('inprogress', 'In progress'), ('lost', 'Lost'), ('won', 'Won'), ('inactive', 'Inactive')], default='new', max_length=25),
        ),
    ]
