# Generated by Django 6.0 on 2026-03-09 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0006_alter_lead_options_alter_lead_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='previous_status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('inprogress', 'In progress'), ('lost', 'Lost'), ('won', 'Won'), ('inactive', 'Inactive')], default='new', max_length=25),
        ),
    ]
