# Generated by Django 6.0 on 2026-04-08 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0007_lead_previous_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leadnote',
            options={'ordering': ['-created_at']},
        ),
    ]
