# Generated by Django 6.0 on 2026-04-08 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_apartament_number_address_apartment_number'),
        ('lead', '0008_alter_leadnote_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='address',
            field=models.ForeignKey(blank=True, help_text='Adress of the lead', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='core.address'),
        ),
    ]
