# Generated by Django 6.0 on 2026-04-16 19:33

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0009_lead_address'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='expected_close_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='last_contacted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='lost_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='lost_reason_details',
            field=models.TextField(blank=True, help_text='Additional context about why the lead is lost'),
        ),
        migrations.AddField(
            model_name='lead',
            name='next_follow_up_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='confidence',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='lead',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='LostReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('category', models.CharField(choices=[('pricing', 'Pricing & Budget'), ('competition', 'Competition'), ('product_fit', 'Product Fit'), ('timing', 'Timing'), ('decision', 'Decision Making'), ('engagement', 'Engagement'), ('organizational', 'Organizational'), ('other', 'Other')], max_length=30)),
                ('description', models.TextField(blank=True, help_text='Internal note about when to use this reason')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide without deleting')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower values show first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_lost_reasons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lost Reason',
                'verbose_name_plural': 'Lost Reasons',
                'ordering': ['category', 'display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='lost_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='lead.lostreason'),
        ),
    ]
