# Generated by Django 6.0 on 2026-04-16 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0010_lead_expected_close_date_lead_last_contacted_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='estimated_value',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
    ]
