# Generated by Django 6.0 on 2026-03-19 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50)),
                ('county', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=100)),
                ('street_number', models.CharField(max_length=50)),
                ('building', models.CharField(blank=True, max_length=50, null=True)),
                ('floor', models.CharField(blank=True, max_length=10, null=True)),
                ('apartament_number', models.CharField(blank=True, max_length=10, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
