# Generated by Django 6.0 on 2026-03-19 22:14

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_adress_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='country',
            field=django_countries.fields.CountryField(default='RO', max_length=2),
        ),
    ]
