# Generated by Django 6.0 on 2026-04-08 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_address_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='apartament_number',
            new_name='apartment_number',
        ),
    ]
