# Generated by Django 6.0 on 2026-05-11 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_team'),
        ('team', '0003_team_invite_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='team.team'),
        ),
    ]
